version: '3.8'

services:
  whoami:
    image: containous/whoami    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefik
    deploy:
      replicas: 1
    logging:
      driver: loki
      options:
        loki-url: "http://logging_loki:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"       
networks:
  traefik:
    external: true
