version: '3.8'

services:
  whoami:
    image: containous/whoami
    networks:
      - traefik      
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}.rule=PathPrefix(`/whoami`)"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}   
        loki-external-labels: "swarm_stack=${SERVICE_NAME}"
networks:
  traefik:
    external: true  
    name: traefik
