version: '3.8'

services:
  whoami:
    image: containous/whoami
    networks:
      - traefik      
    deploy:
      replicas: 1
      placement:
        constraints: ["${NODE}"]        
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-domain.entrypoints=web"
      - "traefik.http.routers.whoami-domain.rule=Host(`whoami.martinfabregues.com`)"
      - "traefik.http.services.whoami-domain.loadbalancer.server.port=80"
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}   
networks:
  traefik:
    external: true  
    name: traefik
