version: '3.8'

services:
  whoami:
    image: containous/whoami    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}-http.entrypoints=web"
      - "traefik.http.services.${SERVICE_NAME}-http.loadbalancer.server.port=80"
      - "traefik.http.routers.${SERVICE_NAME}-http.rule=Path(`/whoami`)"
    networks:
      - traefik
    deploy:
      replicas: 1

networks:
  traefik:
    external: true
