version: '3.8'

services:
  whoami:
    image: containous/whoami
    networks:
      - traefik      
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.100.178:3100/loki/api/v1/push"
        loki-external-labels: "swarm_stack=whoami"
          
networks:
  traefik:
    external: true  
    name: traefik
